---
- name: RHEL.ai Ansible playbook
  hosts: all
  remote_user: root
  vars:
    api_key: "{{ lookup('ansible.builtin.env', 'IBMCLOUD_APIKEY') }}"
    secret_manager_instance_id: "{{ SM_INSTANCE }}"
    secret_ssl_cert_id: "{{ SM_SSL_CERT_ID }}"
    region: "{{ REGION }}"
    hostname_vault: "https://{{ secret_manager_instance_id }}.{{ region }}.secrets-manager.appdomain.cloud"
  roles:
    - ilab
    - proxy
  