---
- name: RHEL.ai ilab Ansible playbook
  hosts: all
  remote_user: root
  vars:
    model_repo: "{{ lookup('ansible.builtin.env', 'MODEL_REPO') }}"
    model_name: "{{ lookup('ansible.builtin.env', 'MODEL_NAME') }}"
    region: "{{ lookup('ansible.builtin.env', 'REGION') }}"
    cos_bucket_name: "{{ lookup('ansible.builtin.env', 'BUCKET_NAME') }}"    
  roles:
    - ilab    
  